In [ ]:
a = int(input("please give a number:"))
print( a )
a += 10
print( a )
print("hello world")
print("enter your code in this small box, and cilck > to start ")

In [ ]:
# this is a new piece of code
# add your code below
import random
b = int(input("please guess a number"))
target = random.randint(1, 100)
while(b != target):
  if(b < target):
    print("give ma a larger number")
    b = int(input("please guess a number"))
  elif( b > target):
    print("give me a smaller number")
    b = int(input("please guess a number"))
print("you win, target is: ", target)


这是一个文本格子，可以在这里做注释
以上的内容是我的python复健项目

In [ ]:
# 9月4号，复习python
# list comprehension
# 格式：
# <new-list-name> = [<expression> for <elements> in <list-name> if <condition>]
# 示例：
from math import sqrt
nums1 = [ sqrt(x) for x in range(1, 30) if (x % 4)]
print(nums1)
# output: 1.0, 1.414, 1.732, ...

# dictionary comprehension
# 格式：
# <new-dictionary-name> = {x : <expression> for <elements> in <list-name> if <condition>}
nums2 = [1, 2, 3, 4]
nums3 = {x: x**2 for x in nums2}
print(nums3)
# output:{1:1, 2: 4, 3: 9, 4: 16}

# set comprehension:
# 格式：
# <new-set-name> = {<expression> for <elements> in <list-name> if <condition>}
# 示例：
nums4 = {int(sqrt(i)) for i in range(30)}
print(nums4)
# output；{0, 1, 2, 3, 4, 5}


# tuple:
#  tuple is in many ways similar to a list; one of the most important
#  differences is that tuples can be used as keys in dictionaries and as elements
#  of sets, while lists cannot.
# example:
d = {(x, x + 1): x for x in range(10)} # Create a dictionary with tuple keys

t = (5, 6)          # Create a tuple
print(type(t))      # Print "<class 'tuple'>"
print(d[t])         # Print "5"
print(d[(1, 2)]) # Print "1"


# parallel iteration: 使用zip（）将多个list, set, ...连在一起
# 这样在进行loop的时候能joint together
# 示例：
fruits = ['apple', 'peach', 'banana', 'guava', 'papaya']
colors = ['red', 'pink', 'yellow', 'green', 'orange', 'black']
for name, color in zip(fruits, colors):
  print(name, 'is', color)
# output:
'''
apple is red
peach is pink
banana is yellow
guava is green
papaya is orange
'''
# 注意事项：由于color的长度更长，所以进行for loop的时候只会loop长度更短的那个
# 所以，black不会输出


# function: parameter passing
# 我们可以使用 * 来传递一堆arguments
# 示例：
def print_months(*months):
  print("The last month is " + months[-1])
# Print "The last month is December"
print_months("January", "Febuary", "March", "April", "May", "June",
"July", "August", "September", "October",
"November", "December")

# 需要注意的是：这里的argument都是以tuple形式传过去的，不能更改
# 如果使用 ** 来传递一堆arguments,会以dictionary的形式传过去

# 格式：
# def <function-name>(**<argument-name>):
#   ...(<argument-name>["<key>"]...)
# <function-name>(key = "...", ...)

# 示例：
def print_month(**month):
  print("The month is " + month["name"] + ", it is the " +
  month["order"] + "th month, it has " + month["days"] +
  " days.")
# Print "The month is September, it is the 9th month, it has 30 days."
print_month(name = "September", order = "9", days = "30")

# python里面也有protected和private的data
# 如何标注这些data？
# 在前面加上"_"是protect data，在前面加上"__"是private的data
# 但是实际上"__"在编译器处理的时候只是将这个变量重命名为
# _<class-name>__<variable-name>
# 它虽然仍然是一个protected data，但名字变了，这样子类就无法干扰父类
# 但是，一般来说这个不重要，因为即使非法访问也不会crush，只有warning罢了。
# 示例：
class Pokemon:
  # class variable: 相当于C++中的static data member
  pokemon_num = 0
  # 这个相当于constructor
  def __init__(self, name = 'Pikachu',
            index = '0025',
            types = 'electric'):
    # private instance variables
    self.__name = name
    self.__index = index
    self.__types = types
    Pokemon.pokemon_num += 1  # 每创建一个新的object,计数加一
  # accessor
  def print(self):
    print('---print Pokemon---')
    print('Name: '+self.__name)
    print('Index:'+self.__index)
    print('Types:'+self.__types)
  # mutator
  def set_name(self, name):
    self.__name = name
  def set__index(self, index):
    self.__index = index
  def set_types(self, types):
    self.__types = types

vulpix = Pokemon('Vulpix', '0037', 'Fire')
# error
# print('Name: ' + vulpix.__name)   # Attribute Error: ... object has no attribute ...
# print('Index: ' + vulpix.__index)
# print('Type: ' + vulpix.__types)
# Okay, but do not work
vulpix.__name = 'AlolanVulpix'
vulpix.__types = 'Ice'
# okay
vulpix.print()
togepi = Pokemon('Togepi', '0175', 'Fairy')
togepi.print()
print("Total Pokemon number is: ", Pokemon.pokemon_num)

[1.0, 1.4142135623730951, 1.7320508075688772, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 3.0, 3.1622776601683795, 3.3166247903554, 3.605551275463989, 3.7416573867739413, 3.872983346207417, 4.123105625617661, 4.242640687119285, 4.358898943540674, 4.58257569495584, 4.69041575982343, 4.795831523312719, 5.0, 5.0990195135927845, 5.196152422706632, 5.385164807134504]
{1: 1, 2: 4, 3: 9, 4: 16}
{0, 1, 2, 3, 4, 5}
apple is red
peach is pink
banana is yellow
guava is green
papaya is orange
The last month is December
The month is September, it is the 9th month, it has 30 days.


AttributeError: 'Pokemon' object has no attribute '__name'

In [ ]:
# 9月7号，复习python
# inheritance: 一种允许我们在已有的class上面搭建新的class的方式
# 所有的attribute和method都会在子类里面得到继承
# 格式：
'''
class <child-class-name> (<parent-class-name>):
  def __init__(self, <arg1>, <arg2>, ...):
    super().__init__(<parent-class-attributes>)
    self.<instance-variable1> = <value1>
    self.<instance-variable2> = <value2>
    ...
  def <function-name>(self, <parameter-list>):
    <function body>
'''
# 使用我们之前创建的class作为parent class
class Pokemon:
  # class variable: 相当于C++中的static data member
  pokemon_num = 0
  # 这个相当于constructor
  def __init__(self, name = 'Pikachu',
            index = '0025',
            types = 'electric'):
    # private instance variables
    self.__name = name
    self.__index = index
    self.__types = types
    Pokemon.pokemon_num += 1  # 每创建一个新的object,计数加一
  # accessor
  def print(self):
    print('---print Pokemon---')
    print('Name: '+self.__name)
    print('Index:'+self.__index)
    print('Types:'+self.__types)
  # mutator
  def set_name(self, name):
    self.__name = name
  def set__index(self, index):
    self.__index = index
  def set_types(self, types):
    self.__types = types

# 这是child class：
class Evol_Pokemon(Pokemon):
  def __init__(self, name = 'Pikachu', index = '0025', types = 'Electric',
            evol = 'Raichu'):
    # invoke parent class init:
    super().__init__(name, index, types)
    self.__evol = evol
  def set_evol(self, evol):
    self.__evol = evol
  def print(self):
    # invoke parent class的print:
    super().print()
    print('Evolve into: ', self.__evol)

jigglypuff = Evol_Pokemon('Jigglypuff', '0039', 'Normal', 'Wigglytuff')
jigglypuff.print()


# library:
# 格式：
# import特定东西
# from [module] import [function/class/variable]
# from [package].[module] import [function/class/variable]

# from [module] import * 这个表示import所有东西

# 还有import...as...
# 这个表示import进来的函数会换一种名称，一般是简写
# 例如：import numpy as np
#    import pandas as pd
# 如果使用from...import <name>
# 你可以直接写<name>调用这个函数
# 但是如果你使用import <package-name>.<module-name>.<function-name>
# 你在使用这个函数时，你需要写：<package-name>.<module-name>.<function-name>


---print Pokemon---
Name: Jigglypuff
Index:0039
Types:Normal
Evolve into:  Wigglytuff


In [ ]:
# 9月9号
# importing and exporting data
# import panda as pd
# df = pd.read_csv('content/drive/My Drive/... .csv', index_col = False)
# 这里最后那个false意味着，自己生成一个编号的index
# 如果index_col = 0，第一数列会作为index

"""
保存数据使用：
import panda as pd
output = pd.DataFrame({CustomerID}: np.array([1, 2, 3]),
            '': np.array([0, 0, 1]))
output.to_csv('content/drive/My Drive/... .csv', index = False)
"""

# Numpy
import numpy as np
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 6
print(a)
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)      # 输出：(2, 3), 代表一共2行，一行三个元素
print(b)

c = np.zeros((3, 2))   # 创建一个3*2的全是0的矩阵
print(c)
# C: [[0, 0],
#     [0, 0],
#     [0, 0]]

d = np.full((2, 2), 7) # 创建一个2*2的全是7的矩阵
print(d)
# d: [[7, 7],
#     [7, 7]]

I = np.eye(4)       # 创建一个4*4的indentity martix
print(I)

e = np.random.random((2, 2))  # 创建一个2*2的随机矩阵
print(e)

f = np.ones((3, 2))    # 创建一个3*2的矩阵，全是1
print(f)

print()
print("array slice")    # 注意：slice是前闭后开的区间
n = I[:2, 1:3]      # 这个是shallow copy, 修改slice的数据也会改变源数据
print(n)
n[0, 0] = 88
print(I)

example1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(example1[1: 100: 2])  # 输出：[1, 3, 5, 7, 9]
print(example1[100:200:2])   # 输出：[]
print(example1[ : : -2])   # 输出：[9 7 5 3 1]
print(example1[ :-1: -2])   # 输出：[]
print(example1[ :-3: -1])   # 输出：[9 8]

<class 'numpy.ndarray'>
(3,)
1 2 3
[6 2 3]
(2, 3)
[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.43223721 0.4744771 ]
 [0.95489601 0.58647016]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]

array slice
[[0. 0.]
 [1. 0.]]
[[ 1. 88.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[1 3 5 7 9]
[]
[9 7 5 3 1]
[]
[9 8]


In [10]:
# array indexing
# important notes:
# 1. a[i: -j]这里slicing不会包括第-j号元素
#    example:
#    a = [1, 2, 3, 4]
#    a[1 : -1] = [2, 3], 而不是 [2, 3, 4]
# 2. a[: : -1]只会reverse a的第一个dimension(axis = 0), 不会影响后续的dimension
#    example:
#    a = [[1, 2],
#         [3, 4],
#         [5, 6]]
#    a[: : -1] = [[5, 6],
#                 [3, 4],
#                 [1, 2]]

import numpy as np
a = np.arange(24).reshape(3, 2, 4)
# print(a)
# print('\n')
# a: [[[ 0  1  2  3]
#      [ 4  5  6  7]]
#     [[ 8  9 10 11]
#      [12 13 14 15]]
#     [[16 17 18 19]
#      [20 21 22 23]]]

print(a[:, :, ::-1])
print('\n')
# output:
# [[[ 3  2  1  0]
#   [ 7  6  5  4]]
#  [[11 10  9  8]
#   [15 14 13 12]]
#  [[19 18 17 16]
#   [23 22 21 20]]]

print(a[(a%5 == 0)])
print('\n')
# output:
# [ 0  5 10 15 20]

print(a[::-1])
print('\n')
# output:
# [[[16 17 18 19]
#   [20 21 22 23]]
#  [[ 8  9 10 11]
#   [12 13 14 15]]
#  [[ 0  1  2  3]
#   [ 4  5  6  7]]]

print(a[1, 0, 1:-1])
print('\n')
# output:
# [9 10]
np.dot(a, a.T)

[[[ 3  2  1  0]
  [ 7  6  5  4]]

 [[11 10  9  8]
  [15 14 13 12]]

 [[19 18 17 16]
  [23 22 21 20]]]


[ 0  5 10 15 20]


[[[16 17 18 19]
  [20 21 22 23]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]]]


[ 9 10]




In [ ]:
# 9月11号
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a = np.arange(1, 13).reshape((3, 4))
print(a)
# a: [[1, 2, 3, 4],
#     [5, 6, 7, 8],
#     [9, 10,11,12]]

row_r1 = a[1,: ]   # 得到a的第二行
print(row_r1, row_r1.shape)
# [5, 6, 7, 8]

row_r2 = a[1:2, :]
print(row_r2, row_r2.shape)
# [[5,6,7,8]]

col_r1 = a[:, 1]   # 得到第二列（横置状态）
col_r2 = a[:, 1:2]  # 得到第二列
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

row_r1 = a[1, 2]   # 相当于a[1][2]

print()

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

b = np.array([0, 2, 0, 1])
# 按照b中的数来slicing
print(a[np.arange(4), b]) # 输出 "[ 1 6 7 11]"

# 将1 6 7 11这几个数加10
a[np.arange(4), b] += 10
print(a)

print()

# boolean array indexing
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2) # 在a中找到大于2的数，创建一个新array，如果这个地方的数大于2，填进去true，否则填false
print(bool_idx) # Prints "[[False False]
              #            [ True True]
              #            [ True True]]"
print(a[bool_idx])
print(a[a > 2])   # 这两个都会输出a中大于2的元素，[3, 4, 5, 6]

# data type
print("data type in numpy")
print()
x = np.array([1, 2]) # Let numpy choose the datatype
print(x.dtype) # Prints "int64"

x = np.array([1.0, 2.0]) # Let numpy choose the datatype
print(x.dtype) # Prints "float64"

x = np.array([1, 2], dtype=np.int64) # Force a particular datatype
print(x.dtype) # Prints "int64"
print(type(x)) # Prints "<class 'numpy.ndarray'>"


# array math
print()
# 有一些function可以做element wise on arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x / y)
print(np.divide(x, y))    # 这两个是一样的

# dot product(和之前的"*"不一样)：矩阵乘法
# 使用@进行矩阵乘法
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
# Inner product of vectors; both produce 219
print(np.matmul(v, w))
print(v@w)
# Matrix / vector product; both produce the rank 1 array [29 67]
print(np.matmul(x, v))
print(x@v)
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
# [43 50]]
print(np.matmul(x, y))
print(x@y)

# numpy functions
print()
x = np.array([[1,2],[3,4]])
print(np.sum(x)) # 计算所有元素的和; prints "10"
print(np.sum(x, axis=0)) # 计算每一列的和; prints "[4 6]"
print(np.sum(x, axis=1)) # 计算每一行的和; prints "[3 7]"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
data type in numpy

int64
float64
int64
<class 'numpy.ndarray'>

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
bytestr:bytes = b"Byte String"
strstr:str = u"unicode str string"
print(type(bytestr), type(strstr))
bytestr.decode()
strstr.encode()

(bytes, str)

In [ ]:
# 9月16日
# 如何计算高维array的乘法？
# 一般使用np.matmul来进行处理
# 运算规则：
# 1. 它将最后两个维度视为矩阵，而前面的所有维度视为批处理维度
# 2. broadcast:
# 如果两个array的shape分别是：(a, b, m, n)和(a, b, n, p)
# 那么他们可以直接相乘，如果shape是(a, 1, m, n)和(a, b, n, p)第一个array会在第二个维度上
# broadcast, 变成(a, b, m, n)再进行乘法
# 3. 矩阵乘法：
# 对于每一对批处理维度下的矩阵，独立的进行标准的矩阵乘法
# 例子：
import numpy as np
A = np.array(range(24)).reshape(2, 3, 4)
print(A)
# 这里我们创建了一个shape为2， 3， 4的array

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
B = np.ones((2, 4, 5))
print(B)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
# 这里，我们发现A与B两个矩阵的最后两个维度满足矩阵乘法的要求可以相乘
# 我们需要的操作是：
# 对于批处理维度中的每一个i, 独立的计算A[i] @ B[i]
# 所以，我们的结果 C = A @ B
# 这里，C[0] = A[0] @ B[0]
#    C[1] = A[1] @ B[1]
# 所以，对于高维array的matmul运算：
# (..., m, n) @ (..., n, p) => (..., m, p)
# 本质上是一个批处理操作，只是将最后两个维度的矩阵按批乘在一起
C = A @ B
print(C)
print("C shape is: ", C.shape)
# 这里，C的shape是(2, 3, 5)

[[[ 6.  6.  6.  6.  6.]
  [22. 22. 22. 22. 22.]
  [38. 38. 38. 38. 38.]]

 [[54. 54. 54. 54. 54.]
  [70. 70. 70. 70. 70.]
  [86. 86. 86. 86. 86.]]]
C shape is:  (2, 3, 5)


In [ ]:
# transpose
# 如何找出transpose之后的array？
# 例子：
# arr_T = np.transpose(arr, (2, 0, 1))
# arr[i, j, k] = arr_T [k, i, j]
# 1D array 在 transpose之后不会有变化
arr = np.arange(24).reshape(2, 3, 4)
print(arr)
print("transpose to (3, 2, 4)\n")
arr_T = np.transpose(arr, (1, 0, 2))
print(arr_T)
print("arr[1, 0, 2] = ", arr[1, 0, 2])
print("arr_T[0, 1, 2] = ", arr_T[0, 1, 2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
transpose to (3, 2, 4)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
arr[1, 0, 2] =  14
arr_T[0, 1, 2] =  14


In [ ]:
# Increase the dimension of an array
# 使用：np.newaxis 或者 np.expand_dims()
# 格式：
# 直接在slicing里面加入np.newaxis就行（也可以使用None代替）
# 这里，新插入的axis的长度是1
# 例子：
# arr[:, None, :]
# arr[np.newaxis, ...]
# arr2 = np.expend_dim(arr, )
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = arr1[:, None, :]
arr3 = arr1[..., np.newaxis]
print(arr2)
# output:
#[[[1 2 3]]

# [[4 5 6]]]
print(arr2.shape)
# output: (2, 1, 3)
print(arr3.shape)
# output: (2, 3, 1)

print("\nnow, test copy")
import copy
copy1 = copy.deepcopy(arr1)   # 使用copy也是可以的
print(copy1)
copy1[0][1] = 78
print(copy1)
print(arr1)   # 这里使用的是deepcopy，所以arr1的数据不会修改


[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)
(2, 3, 1)

now, test copy
[[1 2 3]
 [4 5 6]]
[[ 1 78  3]
 [ 4  5  6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# broadcast是后对齐的
# 例子：A: 15*3*5
#    B: 3*1
# 可以broadcast
# 但是：A: 15*3*5
#    B: 15*3
# 不可以

In [ ]:
# task：pairwise Distance
# 和score function有关
x = np.array([[ 8.54, 1.54, 8.12],
        [ 3.13, 8.76, 5.29],
        [ 7.73, 6.71, 1.31]])
y = np.array([[ 8.65, 0.27, 4.67],
        [ 7.73, 7.26, 1.95]])
reshaped_x = x.reshape(3, 1, 3)
reshaped_y = y.reshape(1, 2, 3)
diffs = reshaped_x- reshaped_y
# Output[i, j] represents the distance between x[i] and y[j].
print("Shape of diffs", diffs.shape)  # shape: (3, 2, 3)
print(diffs)
# It is important to see, via
# broadcasting, that diffs[i,j]
# stores x[i]- y[j]!

Shape of diffs (3, 2, 3)
[[[-0.11  1.27  3.45]
  [ 0.81 -5.72  6.17]]

 [[-5.52  8.49  0.62]
  [-4.6   1.5   3.34]]

 [[-0.92  6.44 -3.36]
  [ 0.   -0.55 -0.64]]]


In [ ]:
dists = np.sqrt(np.sum(diffs**2, axis=2)) # 这里axis=2表示最后一个维度，横行
print(dists)
print(dists.shape)  # shape:(3, 2)
# 在我们最后的结果中，dists[i][j]表示x[i]和y[j]的距离

[[ 3.67797499  8.45241977]
 [10.14568381  5.87925165]
 [ 7.32185769  0.84386018]]
(3, 2)
